spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/,file:C://uploadFile/
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: true
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
  #静态文件资源
  static:
    template-page-path: classpath:/templates/
    resources:
      #访问静态资源规则，可配置多个以','或'，'隔离
      - pathPatterns: /**
        #静态资源文件位置，可配置多个以','或'，'隔离
        resourceLocations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/

  datasource:
    zzj1:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@10.11.76.40:1521/gisdb
      username: nocm
      password: nocm#202310
      hikari:
        read-only: false
        connection-timeout: 60000
        idle-timeout: 50000
        validation-timeout: 3000
        max-lifetime: 60000
        login-timeout: 5
        maximum-pool-size: 30
        minimum-idle: 10
    zzj2:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@10.11.76.40:1521/gisdb
      username: nocm
      password: nocm#202310
      #      jdbc-url: jdbc:oracle:thin:@10.11.82.27:1521:XE
      #      username: DBO
      #      password: LchBnF5JmcQ3
      #      driver-class-name: dm.jdbc.driver.DmDriver
      #      jdbc-url: jdbc:dm://192.168.30.152:5236/DBO?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
      #      username: DBO
      #      password: wht43s2MsokDmYfD
      hikari:
        read-only: false
        connection-timeout: 60000
        idle-timeout: 50000
        validation-timeout: 3000
        max-lifetime: 60000
        login-timeout: 5
        maximum-pool-size: 30
        minimum-idle: 10
    zzj3:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@10.11.76.40:1521/gisdb
      username: nocm
      password: nocm#202310
      hikari:
        read-only: false
        connection-timeout: 60000
        idle-timeout: 50000
        validation-timeout: 3000
        max-lifetime: 60000
        login-timeout: 5
        maximum-pool-size: 30
        minimum-idle: 10

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.zzj.sms.entity
  configuration:
    multiple-result-sets-enabled: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    sql-parser-cache: true
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
sign:
  verify: true

async:
  push:
    pool-size:
      core: 100
      max: 100
logging:
  file:
    path: ./log

excluded:
  pages: /zzj/index,/zzj/login,/zzj/logout,/zzj/index.html,/zzj/favicon.ico,/zzj/login.html,/zzj/duty.html,/zzj/duty_result.html,/zzj/three.html,/zzj/off_duty.html,/zzj/off_result.html,/zzj/off_order.html,/zzj/order_result.html,/zzj/faceBind.html,/zzj/ipAdd,/zzj/user/faceCompare,/zzj/user/featureList,/zzj/userCardSync

ocm:
  base-url: http://nocm.wzmtr.com:2443/crew-admin/api
key-cabinet:
  base-url: http://www.keybox21.com:9032/api
  name: admin
  pwd: 123456
  dept: 10000000000000000
